export type MenuItem = {
  id: string;
  code: string;
  name: string;
  category: string;
  description: string;
  image: string;
  price: number;
  available: boolean;
  allergens: string[];
  recipe_version?: number;
};
export type PublicMenu = {
  id: string;
  name: string;
  slug: string;
  demo: boolean;
  acceptingOrders: boolean;
  items: MenuItem[];
};
export type Restaurant = {
  id: string;
  business_id: string;
  slug: string;
  name: string;
  timezone: string;
  demo: boolean;
  accepting_orders: boolean;
  jourvis_mode: "sleeping" | "watch" | "contact" | "buy";
  per_order_limit: number;
  daily_limit: number;
  integrations_ready: boolean;
  seed_date: string;
};
export type OrderStatus = "NEW" | "ACCEPTED" | "PREPARING" | "READY" | "COMPLETED" | "CANCELLED";
export type Order = {
  id: string;
  status: OrderStatus;
  origin: "seed" | "customer" | "manual";
  note: string;
  total: number;
  food_cost: number;
  created_at: string;
  prepared_at: string | null;
  completed_at: string | null;
  cancelled_at: string | null;
  cancellation_reason: string | null;
  station: string;
  items: { name: string; quantity: number; unitPrice: number; recipeVersion: number | null }[];
};
export type Ingredient = {
  id: string;
  code: string;
  name: string;
  unit: string;
  on_hand: number;
  reserved: number;
  average_cost: number;
  reorder_at: number;
  incoming: number;
};
export type Supplier = {
  id: string;
  name: string;
  contact_email: string;
  phone: string;
  areas: string;
  lead_days: number;
  minimum_order: number;
  terms: string;
  demo: boolean;
  linkStatus: string;
};
export type SupplierProduct = {
  id: string;
  supplier_id: string;
  sku: string;
  name: string;
  category: string;
  unit: string;
  pack_size: number;
  pack_price: number;
  available: boolean;
  version: number;
};
export type Purchase = {
  id: string;
  restaurant_id: string;
  supplier_id: string;
  product_id: string;
  ingredient_id: string;
  packs: number;
  pack_size: number;
  pack_price: number;
  delivery_fee: number;
  status: string;
  received: number;
  version: number;
  approved_version: number | null;
  hard_pack_limit: number;
  target_pack_price: number;
  auto_pack_limit: number;
  terms: string;
  origin: string;
  created_at: string;
};
export type Activity = {
  id: number;
  kind: string;
  record_id: string;
  summary: string;
  details: Record<string, unknown>;
  created_at: string;
};
export type Snapshot = {
  rules: {
    ingredient_id: string;
    product_id: string;
    packs: number;
    enabled: boolean;
    target_pack_price: number;
    auto_pack_limit: number;
    hard_pack_limit: number;
    approved_terms: string;
  }[];
  members: { userId: string; email: string; role: string; status: string }[];
  restaurant: Restaurant;
  role: "owner" | "admin" | "editor" | "viewer";
  orders: Order[];
  menu: MenuItem[];
  ingredients: Ingredient[];
  recipes: { menu_item_id: string; ingredient_id: string; quantity: number; version: number }[];
  suppliers: Supplier[];
  supplierProducts: SupplierProduct[];
  purchases: Purchase[];
  activity: Activity[];
  jobs: {
    id: string;
    kind: string;
    status: string;
    created_at: string;
    error_code: string;
    provider_receipt: string;
  }[];
  stations: { id: string; label: string; enabled: boolean; token: string | null }[];
  daily: { day: string; origin: string; orders: number; sales: number; food_cost: number }[];
  bestSellers: { name: string; quantity: number; sales: number }[];
  movements: {
    id: string;
    ingredient_id: string;
    kind: string;
    quantity: number;
    unit_cost: number;
    reason: string;
    created_at: string;
  }[];
};
export type Business = { id: string; businessId: string; name: string; slug: string; role: string };
export type SupplierSnapshot = {
  suppliers: Supplier[];
  products: SupplierProduct[];
  requests: (Purchase & { restaurant: string })[];
};
