/** Archived 2025 names/amounts; demo selections, never a verified current menu. */
export type MenuRow = readonly [key: string, name: string, category: string, pricePesos: number, sourceId: string | null, description: string, aliases: readonly string[], variant: string | null, dishKey: string, printedName: string];
function row(key: string, name: string, category: string, price: number, source: string | null, description: string, aliases: readonly string[] = [], variant: string | null = null, dishKey = key, printedName = name): MenuRow {
  return [key, name, category, price, source, description, aliases, variant, dishKey, printedName];
}
const starter = 'menu_starters', pasta = 'menu_pasta', mains = 'menu_mains', desserts = 'menu_desserts', drinks = 'menu_drinks';
export const marinaraMenuRows: readonly MenuRow[] = [
  row("spicy_grilled_octopus", "Spicy Grilled Octopus", "Starter", 420, starter, "Grilled octopus with a warming, savory finish.", ["grilled octopus","octopus"]),
  row("buffalo_wings", "Buffalo Wings", "Starter", 400, starter, "Chicken wings with a tangy buffalo-style coating.", ["buffalo chicken wings"]),
  row("parmesan_wings", "Parmesan Wings", "Starter", 400, starter, "Chicken wings with a savory Parmesan-style finish.", ["cheese wings"]),
  row("steam_mussels_scallops", "Steam Mussels & Scallops", "Starter", 535, starter, "Mussels and scallops for the seafood side of the table.", ["steamed mussels and scallops"]),
  row("truffle_spinach_artichoke", "Truffle Spinach & Artichoke", "Starter", 420, starter, "A rich spinach-and-artichoke starter with truffle-style notes.", ["spinach artichoke"]),
  row("italian_potato_croquetas", "Italian Potato Croquetas", "Starter", 385, starter, "Crisp potato bites inspired by the bistro menu.", ["potato croquettes"]),
  row("garlic_shrimp_jalapeno", "Garlic Shrimp in Jalapeño", "Starter", 485, starter, "Shrimp with garlic and a jalapeño-style lift.", ["garlic shrimp","jalapeno shrimp"]),
  row("spicy_calamari_flowerettes_regular", "Spicy Calamari Flowerettes (Regular)", "Starter", 435, starter, "Flower-cut calamari with a crisp exterior.", ["calamari flowerette regular","spicy calamari regular","calamari","calamari flowerette"], "Regular", "spicy_calamari_flowerettes", "Spicy Calamari Flowerettes"),
  row("spicy_calamari_flowerettes_sharing", "Spicy Calamari Flowerettes (Sharing)", "Starter", 585, starter, "Flower-cut calamari with a crisp exterior.", ["calamari flowerette sharing","spicy calamari sharing"], "Sharing", "spicy_calamari_flowerettes", "Spicy Calamari Flowerettes"),
  row("chicken_nuggets", "Chicken Nuggets", "Appetizer", 335, starter, "An informal bistro bite for the table."),
  row("french_fries", "French Fries", "Appetizer", 300, starter, "An informal bistro bite for the table."),
  row("cheesy_fries", "Cheesy Fries", "Appetizer", 325, starter, "An informal bistro bite for the table."),
  row("sour_cream_fries", "Sour Cream Fries", "Appetizer", 325, starter, "An informal bistro bite for the table."),
  row("nachos_overload", "Nachos Overload", "Appetizer", 405, starter, "An informal bistro bite for the table."),
  row("beef_quesadilla", "Beef Quesadilla", "Appetizer", 345, starter, "An informal bistro bite for the table."),
  row("cheese_quesadilla", "Cheese Quesadilla", "Appetizer", 330, starter, "An informal bistro bite for the table."),
  row("shrimple_solo", "Shrimple (Solo)", "Salad", 485, starter, "A lighter option from the photographed salad selection.", ["shrimple"], "Solo", "shrimple", "Shrimple"),
  row("honey_mint_melon_solo", "Honey Mint Melon (Solo)", "Salad", 485, starter, "A lighter option from the photographed salad selection.", ["honey mint melon"], "Solo", "honey_mint_melon", "Honey Mint Melon"),
  row("arugula_peach_pecan_solo", "Arugula with Peach & Pecan (Solo)", "Salad", 465, starter, "A lighter option from the photographed salad selection.", ["arugula with peach & pecan"], "Solo", "arugula_peach_pecan", "Arugula with Peach & Pecan"),
  row("pomelo_shrimp_solo", "Pomelo & Shrimp (Solo)", "Salad", 485, starter, "A lighter option from the photographed salad selection.", ["pomelo & shrimp"], "Solo", "pomelo_shrimp", "Pomelo & Shrimp"),
  row("shrimp_cranberry_salad_solo", "Shrimp & Cranberry Salad (Solo)", "Salad", 485, starter, "A lighter option from the photographed salad selection.", ["shrimp & cranberry salad"], "Solo", "shrimp_cranberry_salad", "Shrimp & Cranberry Salad"),
  row("creamy_tuscan", "Creamy Tuscan", "Soup", 235, starter, "A warming soup to begin a bistro meal.", ["creamy tuscan soup"]),
  row("sweet_potato_soup", "Sweet Potato", "Soup", 195, starter, "A warming soup to begin a bistro meal.", ["sweet potato soup"]),
  row("tomato_basil_soup", "Tomato Basil", "Soup", 225, starter, "A warming soup to begin a bistro meal.", ["tomato basil soup"]),
  row("seafood_marinara_solo", "Seafood Marinara (Solo)", "Pasta", 565, pasta, "Seafood pasta with a tomato-led marinara profile.", ["marinara pasta","seafood pasta"], "Solo", "seafood_marinara", "Seafood Marinara"),
  row("spicy_shrimp_fett_verde_solo", "Spicy Shrimp in Fett Verde (Solo)", "Pasta", 460, pasta, "Shrimp and green pasta with a spicy character.", ["spicy shrimp pasta","fett verde"], "Solo", "spicy_shrimp_fett_verde", "Spicy Shrimp in Fett Verde"),
  row("creamy_beef_steak_tagliatelli_solo", "Creamy Beef Steak Tagliatelli (Solo)", "Pasta", 575, pasta, "Beef and ribbon pasta in a creamy bistro-style sauce.", ["beef tagliatelle","beef pasta"], "Solo", "creamy_beef_steak_tagliatelli", "Creamy Beef Steak Tagliatelli"),
  row("shrimp_mushroom_alfredo_solo", "Shrimp & Mushroom Alfredo (Solo)", "Pasta", 460, pasta, "Shrimp and mushroom pasta with an Alfredo-style sauce.", ["shrimp alfredo","mushroom alfredo"], "Solo", "shrimp_mushroom_alfredo", "Shrimp & Mushroom Alfredo"),
  row("baked_lasagna_solo", "Baked Lasagna (Solo)", "Pasta", 460, pasta, "Layered baked pasta from the photographed menu.", ["lasagna","lasagne"], "Solo", "baked_lasagna", "Baked Lasagna"),
  row("spag_alle_vongole_solo", "Spag Alle Vongole (Solo)", "Pasta", 460, pasta, "Clam pasta from the photographed Italian selection.", ["vongole","clam pasta"], "Solo", "spag_alle_vongole", "Spag Alle Vongole"),
  row("chicken_spinach_carbonara_solo", "Chicken Spinach Carbonara (Solo)", "Pasta", 460, pasta, "Chicken and spinach pasta with a creamy carbonara-style finish.", ["spinach carbonara","chicken carbonara"], "Solo", "chicken_spinach_carbonara", "Chicken Spinach Carbonara"),
  row("spaghetti_bolognese_meatballs_solo", "Spaghetti Bolognese Meatballs (Solo)", "Pasta", 475, pasta, "Spaghetti with meatballs and a tomato-rich sauce.", ["bolognese","spaghetti meatballs"], "Solo", "spaghetti_bolognese_meatballs", "Spaghetti Bolognese Meatballs"),
  row("fettucine_truffle_prosciutto_solo", "Fettucine Truffle & Prosciutto (Solo)", "Pasta", 575, pasta, "Ribbon pasta with truffle-style richness and prosciutto.", ["fettuccine truffle prosciutto","truffle pasta"], "Solo", "fettucine_truffle_prosciutto", "Fettucine Truffle & Prosciutto"),
  row("seafood_marinara_sharing", "Seafood Marinara (Sharing)", "Pasta", 755, pasta, "The sharing format listed separately in the archived menu.", ["seafood marinara sharing"], "Sharing", "seafood_marinara", "Seafood Marinara"),
  row("shrimp_mushroom_alfredo_sharing", "Shrimp & Mushroom Alfredo (Sharing)", "Pasta", 665, pasta, "The sharing format listed separately in the archived menu.", ["shrimp & mushroom alfredo sharing"], "Sharing", "shrimp_mushroom_alfredo", "Shrimp & Mushroom Alfredo"),
  row("chicken_spinach_carbonara_sharing", "Chicken Spinach Carbonara (Sharing)", "Pasta", 665, pasta, "The sharing format listed separately in the archived menu.", ["chicken spinach carbonara sharing"], "Sharing", "chicken_spinach_carbonara", "Chicken Spinach Carbonara"),
  row("shrimp_mushroom_alfredo_cheese_wheel", "Shrimp & Mushroom Alfredo (Cheese Wheel, Solo)", "Cheese Wheel", 750, pasta, "The separately listed cheese-wheel preparation, not a surcharge added to regular pasta.", ["shrimp & mushroom alfredo cheese wheel","cheese wheel shrimp & mushroom alfredo"], "Cheese Wheel · Solo", "shrimp_mushroom_alfredo", "Shrimp & Mushroom Alfredo"),
  row("chicken_spinach_carbonara_cheese_wheel", "Chicken Spinach Carbonara (Cheese Wheel, Solo)", "Cheese Wheel", 750, pasta, "The separately listed cheese-wheel preparation, not a surcharge added to regular pasta.", ["chicken spinach carbonara cheese wheel","cheese wheel chicken spinach carbonara"], "Cheese Wheel · Solo", "chicken_spinach_carbonara", "Chicken Spinach Carbonara"),
  row("fettucine_truffle_prosciutto_cheese_wheel", "Fettucine Truffle & Prosciutto (Cheese Wheel, Solo)", "Cheese Wheel", 850, pasta, "The separately listed cheese-wheel preparation, not a surcharge added to regular pasta.", ["fettucine truffle & prosciutto cheese wheel","cheese wheel fettucine truffle & prosciutto"], "Cheese Wheel · Solo", "fettucine_truffle_prosciutto", "Fettucine Truffle & Prosciutto"),
  row("artichoke_spinach_pizza_12", "Artichoke w/ Spinach Cream Sauce Pizza (12-inch)", "Pizza", 675, pasta, "An Italian-American pizza selection in the photographed size.", ["artichoke w/ spinach cream sauce 12-inch","artichoke w/ spinach cream sauce pizza 12"], "12-inch", "artichoke_spinach_pizza", "Artichoke w/ Spinach Cream Sauce"),
  row("artichoke_spinach_pizza_14", "Artichoke w/ Spinach Cream Sauce Pizza (14-inch)", "Pizza", 795, pasta, "An Italian-American pizza selection in the photographed size.", ["artichoke w/ spinach cream sauce 14-inch","artichoke w/ spinach cream sauce pizza 14"], "14-inch", "artichoke_spinach_pizza", "Artichoke w/ Spinach Cream Sauce"),
  row("salami_piccante_pizza_12", "Salami Piccante Pizza (12-inch)", "Pizza", 645, pasta, "An Italian-American pizza selection in the photographed size.", ["salami piccante 12-inch","salami piccante pizza 12"], "12-inch", "salami_piccante_pizza", "Salami Piccante"),
  row("salami_piccante_pizza_14", "Salami Piccante Pizza (14-inch)", "Pizza", 780, pasta, "An Italian-American pizza selection in the photographed size.", ["salami piccante 14-inch","salami piccante pizza 14"], "14-inch", "salami_piccante_pizza", "Salami Piccante"),
  row("chicken_buffalo_pizza_12", "Chicken Buffalo Pizza (12-inch)", "Pizza", 645, pasta, "An Italian-American pizza selection in the photographed size.", ["chicken buffalo 12-inch","chicken buffalo pizza 12"], "12-inch", "chicken_buffalo_pizza", "Chicken Buffalo"),
  row("chicken_buffalo_pizza_14", "Chicken Buffalo Pizza (14-inch)", "Pizza", 780, pasta, "An Italian-American pizza selection in the photographed size.", ["chicken buffalo 14-inch","chicken buffalo pizza 14"], "14-inch", "chicken_buffalo_pizza", "Chicken Buffalo"),
  row("quattro_formaggi_pizza_12", "Quattro Formaggi Pizza (12-inch)", "Pizza", 680, pasta, "An Italian-American pizza selection in the photographed size.", ["quattro formaggi 12-inch","quattro formaggi pizza 12"], "12-inch", "quattro_formaggi_pizza", "Quattro Formaggi"),
  row("quattro_formaggi_pizza_14", "Quattro Formaggi Pizza (14-inch)", "Pizza", 795, pasta, "An Italian-American pizza selection in the photographed size.", ["quattro formaggi 14-inch","quattro formaggi pizza 14"], "14-inch", "quattro_formaggi_pizza", "Quattro Formaggi"),
  row("beef_angus_tartufata_pizza_12", "Beef Angus Tartufata Pizza (12-inch)", "Pizza", 715, pasta, "An Italian-American pizza selection in the photographed size.", ["beef angus tartufata 12-inch","beef angus tartufata pizza 12"], "12-inch", "beef_angus_tartufata_pizza", "Beef Angus Tartufata"),
  row("beef_angus_tartufata_pizza_14", "Beef Angus Tartufata Pizza (14-inch)", "Pizza", 835, pasta, "An Italian-American pizza selection in the photographed size.", ["beef angus tartufata 14-inch","beef angus tartufata pizza 14"], "14-inch", "beef_angus_tartufata_pizza", "Beef Angus Tartufata"),
  row("classic_margherita_pizza_12", "Classic Margherita Pizza (12-inch)", "Pizza", 635, pasta, "An Italian-American pizza selection in the photographed size.", ["classic margherita 12-inch","classic margherita pizza 12"], "12-inch", "classic_margherita_pizza", "Classic Margherita"),
  row("classic_margherita_pizza_14", "Classic Margherita Pizza (14-inch)", "Pizza", 770, pasta, "An Italian-American pizza selection in the photographed size.", ["classic margherita 14-inch","classic margherita pizza 14"], "14-inch", "classic_margherita_pizza", "Classic Margherita"),
  row("burrata_pizza", "Burrata", "Pizza", 999, pasta, "The burrata item on the photographed pizza page; size and inclusions require confirmation.", ["burrata pizza"]),
  row("truffle_mushroom_burger", "Truffle & Mushroom Burger", "Sandwich & Burger", 565, mains, "A hearty burger from the bistro side of the photographed menu."),
  row("bacon_cheesy_burger", "Bacon Cheesy Burger", "Sandwich & Burger", 525, mains, "A hearty burger from the bistro side of the photographed menu."),
  row("jawbreaker_burger", "Jawbreaker Burger", "Sandwich & Burger", 685, mains, "A hearty burger from the bistro side of the photographed menu."),
  row("hawaiian_burger", "Hawaiian Burger", "Sandwich & Burger", 525, mains, "A hearty burger from the bistro side of the photographed menu."),
  row("braised_beef_shortribs", "Braised Beef Shortribs", "Entree", 895, mains, "A main-course option from the archived bistro menu.", ["short ribs","beef short ribs"], "Regular"),
  row("tomahawk_porkchop", "Tomahawk Porkchop", "Entree", 785, mains, "A main-course option from the archived bistro menu.", ["tomahawk pork chop"], "Regular"),
  row("roasted_pork_cutlet", "Roasted Pork Cutlet", "Entree", 785, mains, "A main-course option from the archived bistro menu.", ["pork cutlet"], "Regular"),
  row("classic_fish_crisps", "Classic Fish & Crisps", "Entree", 565, mains, "A main-course option from the archived bistro menu.", ["fish and chips"], "Regular"),
  row("herb_spring_chicken_mushroom", "Herb Spring Chicken in Mushroom", "Entree", 595, mains, "A main-course option from the archived bistro menu.", ["herb spring chicken","roast chicken"], "Regular"),
  row("grilled_salmon", "Grilled Salmon", "Entree", 995, mains, "A main-course option from the archived bistro menu.", ["salmon"], "Regular"),
  row("grilled_swordfish_bouillabaisse", "Grilled Swordfish Bouillabaisse", "Entree", 755, mains, "A main-course option from the archived bistro menu.", ["swordfish"], "Regular"),
  row("seafood_tomato_risotto_porcini", "Seafood Tomato Risotto with Porcini", "Entree", 635, mains, "A main-course option from the archived bistro menu.", ["seafood risotto"], "Regular"),
  row("baby_backribs_regular", "Baby Backribs (Regular)", "Entree", 985, mains, "A main-course option from the archived bistro menu.", ["baby back ribs","ribs regular"], "Regular", "baby_backribs", "Baby Backribs"),
  row("chicken_piccata", "Chicken Piccata", "Entree", 565, mains, "A main-course option from the archived bistro menu.", ["piccata"], "Regular"),
  row("baby_backribs_sharing", "Baby Backribs (Sharing)", "Entree", 1700, mains, "The separately priced sharing format of the rib dish.", ["baby back ribs sharing"], "Sharing", "baby_backribs", "Baby Backribs"),
  row("grilled_us_rib_eye", "Grilled US Rib Eye Steak", "Steak", 2350, mains, "A steak selection; cut weight, grade and current sourcing are not verified."),
  row("grilled_us_ny_striploin", "Grilled US NY Striploin Steak", "Steak", 2000, mains, "A steak selection; cut weight, grade and current sourcing are not verified."),
  row("steamed_rice", "Steamed Rice", "Sides", 50, mains, "A separately listed accompaniment; portion size requires confirmation."),
  row("garlic_rice", "Garlic Rice", "Sides", 80, mains, "A separately listed accompaniment; portion size requires confirmation."),
  row("mashed_potato", "Mashed Potato", "Sides", 80, mains, "A separately listed accompaniment; portion size requires confirmation."),
  row("sauteed_mix_vegetables", "Sautéed Mix Vegetables", "Sides", 80, mains, "A separately listed accompaniment; portion size requires confirmation."),
  row("truffle_honey_pizza", "Truffle Honey for Pizza", "Sides", 95, mains, "A separately listed accompaniment; portion size requires confirmation."),
  row("garlic_bread", "Garlic Bread", "Sides", 25, mains, "A separately listed accompaniment; portion size requires confirmation."),
  row("key_lime_cheesecake", "Key Lime Cheesecake", "Desserts", 220, desserts, "A citrus-led cheesecake finish."),
  row("new_york_cheesecake", "New York Style Cheesecake", "Desserts", 325, desserts, "A classic cheesecake option."),
  row("summer_mango_pannacotta", "Summer Mango Pannacotta", "Desserts", 395, desserts, "A mango-led dessert from the photographed menu."),
  row("orange_juice", "Orange Juice", "Fresh Juices", 175, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("cucumber_lemon", "Cucumber Lemon", "Fresh Juices", 175, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("honey_lemon", "Honey Lemon", "Fresh Juices", 175, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("basil_lime_cucumber", "Basil Lime Cucumber", "Fresh Juices", 175, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("lychee_grapemint", "Lychee Grapemint", "Fresh Juices", 175, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("mango_shake", "Mango Shake", "Fresh Fruit Shake", 175, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("watermelon_shake", "Watermelon Shake", "Fresh Fruit Shake", 175, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("pineapple_lemonade", "Pineapple Lemonade", "Mocktail", 175, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("pink_lemonade", "Pink Lemonade", "Mocktail", 175, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("espresso", "Espresso", "Coffee", 140, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("americano", "Americano", "Coffee", 145, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("cappuccino", "Cappuccino", "Coffee", 180, drinks, "A beverage from the photographed menu; size and current recipe require confirmation."),
  row("marinara_bistro_platter", "Marinara Bistro Platter", "Marinara Concepts", 895, null, "Proposed sharing selection of crostini, crisp potato bites and warm cheese dip."),
  row("roasted_tomato_burrata_crostini", "Roasted Tomato & Burrata Crostini", "Marinara Concepts", 395, null, "Proposed toasted bread with roast tomato, creamy burrata and basil."),
  row("truffle_mushroom_arancini", "Truffle Mushroom Arancini", "Marinara Concepts", 385, null, "Proposed crisp risotto bites with mushroom and a truffle-style finish."),
  row("lemon_caper_prawn_linguine", "Lemon-Caper Prawn Linguine", "Marinara Concepts", 565, null, "Proposed prawn linguine with lemon, capers and a light garlic sauce."),
  row("brown_butter_sage_mushroom_pasta", "Brown Butter & Sage Mushroom Pasta", "Marinara Concepts", 495, null, "Proposed mushroom pasta with brown butter and aromatic sage."),
  row("porcini_roast_garlic_pizza", "Porcini & Roast Garlic Pizza", "Marinara Concepts", 725, null, "Proposed pizza with mushrooms, roast garlic and a creamy cheese base."),
  row("orange_rosemary_chicken", "Orange-Rosemary Chicken", "Marinara Concepts", 625, null, "Proposed roast chicken with citrus and rosemary notes."),
  row("marinara_affogato", "Marinara Affogato", "Marinara Concepts", 245, null, "Proposed espresso poured over a vanilla-style frozen dessert."),
  row("basil_citrus_spritz", "Basil Citrus Spritz (Alcohol-free)", "Marinara Concepts", 195, null, "Proposed sparkling citrus refresher with basil; a non-alcoholic demo concept."),
  row("salted_caramel_espresso_pannacotta", "Salted Caramel Espresso Pannacotta", "Marinara Concepts", 295, null, "Proposed panna cotta with coffee and a salted-caramel finish."),
];
